apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ""  # Set this to your actual hostname if needed, else leave empty
      http:
        paths:
          - path: "/"  # Define the path that should be routed
            pathType: Prefix
            backend:
              service:
                name: webhook-receiver  # This must match the service name
                port:
                  number: 9292  # Ensure this matches the service's target port

